load("@rules_python//python:py_binary.bzl", "py_binary")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "export_brewfile_macos",
    srcs = ["generate-brewfile.sh"],
    target_compatible_with = ["@platforms//os:macos"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "export_brewfile_linux",
    srcs = ["generate-brewfile.sh"],
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "export_powertoys_settings",
    srcs = ["export_powertoys_settings.py"],
    legacy_create_init = 0,
    target_compatible_with = ["@platforms//os:windows"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "export_vscode_extensions",
    srcs = ["export_vscode_extensions.py"],
    legacy_create_init = 0,
    target_compatible_with = select({
        "@platforms//os:macos": [],
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["//visibility:public"],
)

py_binary(
    name = "copy_untrap_settings",
    srcs = ["copy_untrap_settings.py"],
    legacy_create_init = 0,
    visibility = ["//visibility:public"],
)
