# env.nu
#
# Installed by:
# version = "0.103.0"
#
# Previously, environment variables were typically configured in `env.nu`.
# In general, most configuration can and should be performed in `config.nu`
# or one of the autoload directories.
#
# This file is generated for backwards compatibility for now.
# It is loaded before config.nu and login.nu
#
# See https://www.nushell.sh/book/configuration.html
#
# Also see `help config env` for more options.
#
# You can remove these comments if you want or leave
# them for future reference.

# =============================================================================
# fzf - mirrors dot_config/zsh/src/fzf.zsh
#
# These must live here rather than in config.nu: the fzf/atuin integration
# scripts land in the vendor autoload dir, which nushell sources *after*
# config.nu, and fzf's `export-env` block reads these variables as it loads.
# The keybindings themselves (ctrl-t / ctrl-r / alt-c) come from
# `fzf --nushell`, generated by run_onchange_after_nushell-integrations.sh.
# =============================================================================
$env.FZF_DEFAULT_COMMAND = 'fd --type f --hidden --follow --exclude .git'
$env.FZF_CTRL_T_COMMAND = $env.FZF_DEFAULT_COMMAND
$env.FZF_ALT_C_COMMAND = 'fd --type d --hidden --follow --exclude .git'

$env.FZF_DEFAULT_OPTS = '
  --height=40%
  --layout=reverse
  --border
  --bind="ctrl-/:toggle-preview"
  --preview="
    if [ -d {} ]; then
      eza --tree --level=2 --color=always -- {}
    elif [ -f {} ] && [ -r {} ]; then
      if command -v bat >/dev/null 2>&1; then
        bat --style=numbers --color=always --line-range :300 -- {} 2>/dev/null || :
      fi
    fi
  "
'

# =============================================================================
# atuin - keep nushell's history in its own store, separate from zsh's.
#
# atuin defaults to ~/.local/share/atuin for every shell, so without this the
# up-arrow search in nushell replays zsh's history and vice versa.
# ATUIN_DATA_DIR relocates the whole set (history.db, records.db, meta.db, key)
# for nushell only; zsh keeps the default directory. It is created on first use
# and starts empty - nushell history accumulates from here on.
#
# ~/.config/atuin/config.toml is still shared, so keymap/search settings stay
# in sync. A separate store does mean a separate encryption key, so if you ever
# `atuin login`, the two shells sync as two independent histories.
# =============================================================================
$env.ATUIN_DATA_DIR = (
  $env.XDG_DATA_HOME?
  | default ($nu.home-dir | path join ".local" "share")
  | path join "atuin-nu"
)