[[snippets]]
    description = "Show recent commit"
    command = "git log --date=short --format=\"%h %ad %s\" -<top_n>"
    tag = ["git"]
[[snippets]]
    description = "Show commit messages in-between within folder"
    command = "git log --format='- %s' <from_commit>..<to_commit> -- $(git rev-parse --show-toplevel)<regex=/*>"
    tag = ["git"]
[[snippets]]
    description = "Prettify a bash/zsh file"
    command = "(d=\"$(pwd)\"; cd \"$HOME\" && shfmt -w -ln=<language=zsh> -i 2 -ci -sr -bn \"$d/<file_name>\")"
    tag = ["prettify", "zsh", "bash"]
[[snippets]]
    description = "Compile template file"
    command = "chezmoi execute-template < $(chezmoi source-path)/<tmpl_file> | bat"
    tag = ["chezmoi"]
[[snippets]]
    description = "List of cask packages"
    command = "brew info --cask --json=v2 $(brew list --cask) | jq -r '.casks[] | select(.depends_on != {}) | .token'"
    tag = ["homebrew"]
[[snippets]]
    description = "List of formula packages"
    command = "brew info --json=v2 --installed | jq -r '.formulae[] | select(.installed[0].installed_on_request == true) | .name'"
    tag = ["homebrew"]
[[snippets]]
    description = "Count file types by extension of the current directory."
    command = "find . -type f -name \"*.*\" | sed 's/.*\\.//' | sort | uniq -c | sort -rn"
    tag = ["file properties"]
[[snippets]]
    description = "Convert zh_CN -> zh_TW from clipboard"
    command = " pbpaste | opencc -c <config=s2twp.json> | pbcopy"
    tag = ["opencc", "zh", "macos"]
[[snippets]]
  description = "Convert zh_CN -> zh_TW from file"
  command = """
 f="<file>" && opencc -c <config=s2twp.json> -i "$f" | sponge "$f"\
"""
  tag = ["prettify", "zh"]
[[snippets]]
  description = "Convert zh_CN -> zh_TW"
  command = " echo \"<text>\" | opencc -c <config=s2twp.json>"
  tag = ["opencc", "zh", "i18n"]
[[snippets]]
  description = "Convert zh_Hant -> 日本新字体"
  command = " echo \"<text>\" | opencc -c t2jp.json"
  tag = ["opencc", "ja"]
[[snippets]]
  description = "Convert 日本新字体 -> zh_Hant"
  command = " echo \"<text>\" | opencc -c jp2t.json"
  tag = ["opencc", "ja"]
[[snippets]]
  description = "Prettify JSON from clipboard."
  command = " pbpaste | jq | pbcopy"
  tag = ["prettify", "jq"]

