#!/usr/bin/env zsh
# vim: filetype=zsh

set -euo pipefail

source "$HOME/.zsh/zsh_python_init.zsh"
python="$(zsh_python_init)"
cd "$(cd_zsh_python)" && exec "$python" -m aws.list_assumable_role --profile "${1:?Usage: $0 <aws-profile>}
