#!/usr/bin/env zsh
# vim: filetype=zsh

set -euo pipefail

source "$HOME/.zsh/zsh_python_init.zsh"
python="$(zsh_python_init)"
cd "$(cd_zsh_python)" && exec "$python" -m sleepwatcher.enable_sleepwatcher
